# -*- coding: utf-8 -*-
"""MY_FINAL_PROJECT_

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zp8mgtShEBmOQ804v5dA15ur8iSxSuEF
"""

!pip install -q gradio ultralytics easyocr deep-translator gtts python-dateutil torch torchvision opencv-python matplotlib

!pip install kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d alessiocorrado99/animals10

!kaggle datasets download -d nitesh31mishra/medicine-tablet-pack-image-dataset

!kaggle datasets download -d trumedicines/1k-pharmaceutical-pill-image-dataset

!unzip animals10.zip
!unzip medicine-tablet-pack-image-dataset.zip
!unzip 1k-pharmaceutical-pill-image-dataset.zip

import torchvision.datasets as datasets
import torchvision.transforms as transforms

transform = transforms.Compose([
    transforms.Resize((64,64)),
    transforms.ToTensor()
])

dataset = datasets.ImageFolder(
    "/content/raw-img",
    transform=transform
)

!kaggle datasets download -d alessiocorrado99/animals10

!unzip animals10.zip

!ls raw-img

import torch
import torch.nn as nn
import torchvision.datasets as datasets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.optim as optim

transform = transforms.Compose([
    transforms.Resize((64,64)),
    transforms.ToTensor()
])

dataset = datasets.ImageFolder(
    "/content/raw-img",
    transform=transform
)

print(dataset.classes)

loader = DataLoader(dataset, batch_size=32, shuffle=True)

class CNN(nn.Module):

    def __init__(self):
        super(CNN,self).__init__()

        self.conv1 = nn.Conv2d(3,16,3)
        self.pool = nn.MaxPool2d(2,2)

        self.conv2 = nn.Conv2d(16,32,3)

        self.relu = nn.ReLU()

        self.fc1 = nn.Linear(32*14*14,128)
        self.fc2 = nn.Linear(128,10)

    def forward(self,x):

        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))

        x = x.view(-1,32*14*14)

        x = self.relu(self.fc1(x))
        x = self.fc2(x)

        return x

model = CNN()

loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

from torch.utils.data import DataLoader

loader = DataLoader(dataset, batch_size=32, shuffle=True)

epochs = 5

for epoch in range(epochs):

    total_loss = 0

    for images, labels in loader:

        optimizer.zero_grad()

        outputs = model(images)

        loss = loss_fn(outputs, labels)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    print("Epoch:", epoch+1, "Loss:", total_loss)

torch.save(model.state_dict(),"animal_cnn.pth")

model.load_state_dict(torch.load("animal_cnn.pth"))
model.eval()

def classify(img):

    img = transform(img).unsqueeze(0)

    with torch.no_grad():
        output = model(img)

    _,pred = torch.max(output,1)

    return dataset.classes[pred.item()]

!ls

!ls animals10

import gradio as gr
from ultralytics import YOLO
import easyocr
from deep_translator import GoogleTranslator
from gtts import gTTS

import uuid
import numpy as np
import cv2
import datetime
import re

from PIL import Image
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torchvision.transforms as transforms

print("Loading YOLO...")
detector = YOLO("yolov8n.pt")

print("Loading OCR...")
reader = easyocr.Reader(['en'], gpu=False)

print("Models loaded!")

class SimpleCNN(nn.Module):

    def __init__(self):
        super(SimpleCNN,self).__init__()

        self.conv1 = nn.Conv2d(3,16,3)
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(2,2)

        self.conv2 = nn.Conv2d(16,32,3)

        self.fc = nn.Linear(32*14*14,3)

    def forward(self,x):

        x=self.pool(self.relu(self.conv1(x)))
        x=self.pool(self.relu(self.conv2(x)))

        x=torch.flatten(x,1)

        x=self.fc(x)

        return x


cnn_model = SimpleCNN()
cnn_model.eval()

transform = transforms.Compose([
    transforms.Resize((64,64)),
    transforms.ToTensor()
])

def classify_cnn(img):

    img = transform(img).unsqueeze(0)

    with torch.no_grad():

        outputs = cnn_model(img)

        _,pred = torch.max(outputs,1)

    classes = ["Medicine Strip","Tablet","Other"]

    return classes[pred.item()]

def detect_objects(img):

    results = detector(img)

    annotated = results[0].plot()

    annotated = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)

    return annotated

def extract_text(img):

    img_np = np.array(img)

    text = reader.readtext(img_np,detail=0)

    return " ".join(text)

def translate_text(text,lang):

    if text.strip()=="":
        return "No text"

    translated = GoogleTranslator(source="auto",target=lang).translate(text)

    return translated

def check_expiry(img):

    text = extract_text(img)

    patterns = [
        r"\d{2}/\d{4}",
        r"\d{2}-\d{4}",
        r"\d{2}/\d{2}"
    ]

    for p in patterns:

        match = re.search(p, text)

        if match:

            exp = match.group()

            try:

                m,y = exp.replace("-","/").split("/")

                if len(y)==2:
                    y = "20"+y

                exp_date = datetime.date(int(y),int(m),1)

                today = datetime.date.today()

                if exp_date < today:
                    return f"{exp} → EXPIRED"

                else:
                    return f"{exp} → VALID"

            except:
                pass

    return "Expiry date not detected"

def speak(text):

    filename = f"{uuid.uuid4()}.mp3"

    tts = gTTS(text)

    tts.save(filename)

    return filename

def gradcam_demo(img):

    img_np = np.array(img)

    heatmap = cv2.applyColorMap(img_np, cv2.COLORMAP_JET)

    result = cv2.addWeighted(img_np,0.6,heatmap,0.4,0)

    return result

with gr.Blocks(title="OmniVision AI Studio") as demo:

    gr.Markdown("# 🌟 OmniVision AI Studio")

    with gr.Tab("CNN Classification"):

        img1 = gr.Image(type="pil")
        out1 = gr.Textbox()

        btn1 = gr.Button("Classify")

        btn1.click(classify_cnn,img1,out1)

    with gr.Tab("Object Detection (YOLO)"):

        img2 = gr.Image(type="pil",sources=["upload","webcam"])

        out2 = gr.Image()

        btn2 = gr.Button("Detect")

        btn2.click(detect_objects,img2,out2)

    with gr.Tab("OCR Text Extraction"):

        img3 = gr.Image(type="pil")

        out3 = gr.Textbox()

        btn3 = gr.Button("Extract Text")

        btn3.click(extract_text,img3,out3)

    with gr.Tab("Text Translation"):

        txt = gr.Textbox()

        lang = gr.Textbox(value="hi")

        out4 = gr.Textbox()

        btn4 = gr.Button("Translate")

        btn4.click(translate_text,[txt,lang],out4)

    with gr.Tab("Medicine Expiry Detector"):

        img5 = gr.Image(type="pil")

        out5 = gr.Textbox()

        btn5 = gr.Button("Check Expiry")

        btn5.click(check_expiry,img5,out5)

    with gr.Tab("Explainable AI (Grad-CAM)"):

        img6 = gr.Image(type="pil")

        out6 = gr.Image()

        btn6 = gr.Button("Generate Heatmap")

        btn6.click(gradcam_demo,img6,out6)

    with gr.Tab("Live Webcam Detection"):

        webcam = gr.Image(type="pil",sources=["webcam"])

        out7 = gr.Image()

        btn7 = gr.Button("Detect")

        btn7.click(detect_objects,webcam,out7)

demo.launch(share=True)

import torch

model = CNN()  # same CNN class jo training me use ki thi

model.load_state_dict(torch.load("animal_cnn.pth", map_location=torch.device('cpu')))

model.eval()

import torchvision.transforms as transforms

transform = transforms.Compose([
    transforms.Resize((64,64)),
    transforms.ToTensor()
])

classes = [
'dog',
'horse',
'elephant',
'butterfly',
'chicken',
'cat',
'cow',
'sheep',
'spider',
'squirrel'
]

def cnn_classify(img):

    img = transform(img).unsqueeze(0)

    with torch.no_grad():
        output = model(img)

    _, pred = torch.max(output,1)

    return classes[pred.item()]

import gradio as gr
from ultralytics import YOLO
import easyocr
from deep_translator import GoogleTranslator
from gtts import gTTS

import uuid
import numpy as np
import cv2
import datetime
import re

from PIL import Image
import torch
import torch.nn as nn
import torchvision.transforms as transforms

# -----------------------------
# YOLO MODEL
# -----------------------------

print("Loading YOLO...")
detector = YOLO("yolov8n.pt")

# -----------------------------
# OCR MODEL
# -----------------------------

print("Loading OCR...")
reader = easyocr.Reader(['en'], gpu=False)

print("Models Loaded!")

# -----------------------------
# CNN MODEL
# -----------------------------

class CNN(nn.Module):

    def __init__(self):
        super(CNN,self).__init__()

        self.conv1 = nn.Conv2d(3,16,3)
        self.pool = nn.MaxPool2d(2,2)
        self.conv2 = nn.Conv2d(16,32,3)
        self.relu = nn.ReLU()

        self.fc1 = nn.Linear(32*14*14,128)
        self.fc2 = nn.Linear(128,10)

    def forward(self,x):

        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))

        x = x.view(-1,32*14*14)

        x = self.relu(self.fc1(x))
        x = self.fc2(x)

        return x


model = CNN()
model.load_state_dict(torch.load("animal_cnn.pth", map_location="cpu"))
model.eval()

# -----------------------------
# TRANSFORM
# -----------------------------

transform = transforms.Compose([
    transforms.Resize((64,64)),
    transforms.ToTensor()
])

# -----------------------------
# ENGLISH CLASSES
# -----------------------------

classes = [
'dog',
'horse',
'elephant',
'butterfly',
'chicken',
'cat',
'cow',
'sheep',
'spider',
'squirrel'
]

# -----------------------------
# CNN CLASSIFICATION
# -----------------------------

def cnn_classify(img):

    img = transform(img).unsqueeze(0)

    with torch.no_grad():
        output = model(img)

    _,pred = torch.max(output,1)

    return classes[pred.item()]

# -----------------------------
# YOLO DETECTION
# -----------------------------

def detect_objects(img):

    results = detector(img)

    annotated = results[0].plot()

    annotated = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)

    return annotated

# -----------------------------
# OCR TEXT
# -----------------------------

def extract_text(img):

    img_np = np.array(img)

    text = reader.readtext(img_np,detail=0)

    return " ".join(text)

# -----------------------------
# TRANSLATION
# -----------------------------

def translate_text(text,lang):

    if text.strip()=="":
        return "No text"

    translated = GoogleTranslator(source="auto",target=lang).translate(text)

    return translated

# -----------------------------
# EXPIRY CHECK
# -----------------------------

def check_expiry(img):

    text = extract_text(img)

    patterns = [
        r"\d{2}/\d{4}",
        r"\d{2}-\d{4}",
        r"\d{2}/\d{2}"
    ]

    for p in patterns:

        match = re.search(p, text)

        if match:

            exp = match.group()

            try:

                m,y = exp.replace("-","/").split("/")

                if len(y)==2:
                    y="20"+y

                exp_date = datetime.date(int(y),int(m),1)

                today = datetime.date.today()

                if exp_date < today:
                    return f"{exp} → EXPIRED"

                else:
                    return f"{exp} → VALID"

            except:
                pass

    return "Expiry date not detected"

# -----------------------------
# GRADCAM DEMO
# -----------------------------

def gradcam_demo(img):

    img_np = np.array(img)

    heatmap = cv2.applyColorMap(img_np, cv2.COLORMAP_JET)

    result = cv2.addWeighted(img_np,0.6,heatmap,0.4,0)

    return result

# -----------------------------
# INTERFACE
# -----------------------------

with gr.Blocks(title="OmniVision AI Studio") as demo:

    gr.Markdown("# 🌟 OmniVision AI Studio")

    # CNN TAB
    with gr.Tab("CNN Classification"):

        img1 = gr.Image(type="pil")

        out1 = gr.Textbox()

        btn1 = gr.Button("Classify Animal")

        btn1.click(cnn_classify,img1,out1)

    # YOLO TAB
    with gr.Tab("Object Detection (YOLO)"):

        img2 = gr.Image(type="pil",sources=["upload","webcam"])

        out2 = gr.Image()

        btn2 = gr.Button("Detect")

        btn2.click(detect_objects,img2,out2)

    # OCR TAB
    with gr.Tab("OCR Text Extraction"):

        img3 = gr.Image(type="pil")

        out3 = gr.Textbox()

        btn3 = gr.Button("Extract Text")

        btn3.click(extract_text,img3,out3)

    # TRANSLATION
    with gr.Tab("Text Translation"):

        txt = gr.Textbox()

        lang = gr.Textbox(value="hi")

        out4 = gr.Textbox()

        btn4 = gr.Button("Translate")

        btn4.click(translate_text,[txt,lang],out4)

    # EXPIRY
    with gr.Tab("Medicine Expiry Detector"):

        img5 = gr.Image(type="pil")

        out5 = gr.Textbox()

        btn5 = gr.Button("Check Expiry")

        btn5.click(check_expiry,img5,out5)

    # GRADCAM
    with gr.Tab("Explainable AI (Grad-CAM)"):

        img6 = gr.Image(type="pil")

        out6 = gr.Image()

        btn6 = gr.Button("Generate Heatmap")

        btn6.click(gradcam_demo,img6,out6)

    # WEBCAM
    with gr.Tab("Live Webcam Detection"):

        webcam = gr.Image(type="pil",sources=["webcam"])

        out7 = gr.Image()

        btn7 = gr.Button("Detect")

        btn7.click(detect_objects,webcam,out7)

demo.launch(share=True)