# -*- coding: utf-8 -*-
"""Object_Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9UpIqas7xln1UYwbt2gXjdDsZTvercb
"""

!pip install ultralytics opencv-python

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

# Load pre-trained YOLOv8 model
model = YOLO("yolov8n.pt")



from google.colab import files
uploaded = files.upload()

for file_name in uploaded.keys():
    results = model(file_name)
    results[0].show()

import cv2

for file_name in uploaded.keys():
    results = model(file_name)
    detected = results[0].plot()
    cv2.imwrite(f"detected_{file_name}", detected)

print("Output images saved!")

from google.colab import files
uploaded = files.upload()

for img in uploaded.keys():
    results = model(img)
    results[0].show()

from google.colab import files
uploaded = files.upload()

for img in uploaded.keys():
    results = model(img)
    results[0].show()

import cv2

for file_name in uploaded.keys():
    results = model(file_name)
    detected = results[0].plot()
    cv2.imwrite(f"detected_{file_name}", detected)

print("Output images saved!")

from google.colab import files
uploaded = files.upload()

for img in uploaded.keys():
    results = model(img)
    results[0].show()

from google.colab import files
uploaded = files.upload()

for img in uploaded.keys():
    results = model(img)
    results[0].show()

from google.colab import files
uploaded = files.upload()

for img in uploaded.keys():
    results = model(img)
    results[0].show()