# -*- coding: utf-8 -*-
"""OCR_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQicnhVKLEyk9QRqALgnHBSWF3jTVlG8
"""

!sudo apt-get install tesseract-ocr
!pip install pytesseract pillow

!sudo apt-get install tesseract-ocr
!pip install pytesseract pillow

from google.colab import files
uploaded = files.upload()

import pytesseract
from PIL import Image

for img_name in uploaded.keys():
    img = Image.open(img_name)
    text = pytesseract.image_to_string(img)
    print("🔍 Extracted Text:")
    print(text)

import matplotlib.pyplot as plt

plt.imshow(img)
plt.axis('off')
print("Extracted Text:")
print(text)

import pytesseract
import cv2
import numpy as np

img_cv = cv2.imread(img_name)
h, w, _ = img_cv.shape

boxes = pytesseract.image_to_boxes(img_cv)

for b in boxes.splitlines():
    b = b.split(' ')
    x1, y1, x2, y2 = int(b[1]), int(b[2]), int(b[3]), int(b[4])
    cv2.rectangle(img_cv, (x1, h-y1), (x2, h-y2), (0,255,0), 2)

plt.imshow(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB))
plt.axis('off')

from google.colab import files
uploaded = files.upload()

import pytesseract
from PIL import Image

for img_name in uploaded.keys():
    img = Image.open(img_name)
    text = pytesseract.image_to_string(img)
    print("Extracted Text:")
    print(text)

from google.colab import files
uploaded = files.upload()

import pytesseract
from PIL import Image

for img_name in uploaded.keys():
    img = Image.open(img_name)
    text = pytesseract.image_to_string(img)
    print("Extracted Text:")
    print(text)

!tesseract --version

!sudo apt-get update
!sudo apt-get install -y tesseract-ocr
!pip install pytesseract pillow

from google.colab import files
uploaded = files.upload()

import pytesseract
from PIL import Image

img_name = list(uploaded.keys())[0]
img = Image.open(img_name)

text = pytesseract.image_to_string(img)
print("Extracted Text:\n")
print(text)