# -*- coding: utf-8 -*-
"""Translation detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrBnQtZTQel4DDv65KLpFQe6JJNHSZaY
"""

# install OCR + translator + image libs — these work well in Colab
!pip install easyocr deep-translator pillow matplotlib

# ✅ TEXT TRANSLATION CODE USING deep-translator

from deep_translator import GoogleTranslator

# Function to translate text
def translate_text(text, target_lang):
    try:
        translated = GoogleTranslator(source='auto', target=target_lang).translate(text)
        return translated
    except Exception as e:
        return f"Error: {e}"

# ---------------------------------------------------------
# USER INPUT ZONE
# ---------------------------------------------------------

text = input("Enter the text you want to translate: ")

print("\nSelect the target language code:")
print("English: en | Hindi: hi | Bengali: bn | Tamil: ta | Telugu: te | Kannada: kn | Malayalam: ml | Spanish: es | French: fr | German: de")

target = input("Enter language code: ")

output = translate_text(text, target)

print("\n🔹 Translated Text:")
print(output)

# Install libraries
!pip install easyocr deep-translator pillow matplotlib

from deep_translator import GoogleTranslator
from google.colab import files
import easyocr
from PIL import Image
import matplotlib.pyplot as plt

reader = easyocr.Reader(['en'])  # OCR reader

# ------------------------------- #
# TRANSLATION FUNCTION
# ------------------------------- #
def translate_text(text, target_lang):
    return GoogleTranslator(source='auto', target=target_lang).translate(text)

# ------------------------------- #
# OCR FUNCTION
# ------------------------------- #
def extract_text_from_image(img_path):
    result = reader.readtext(img_path, detail=0)
    return " ".join(result)

# ------------------------------- #
# MAIN PROGRAM
# ------------------------------- #

print("Select an option:")
print("1 → Type text manually")
print("2 → Upload a text file (.txt)")
print("3 → Upload an image for OCR + translation")

choice = input("Enter 1/2/3: ")

# Manual text input
if choice == "1":
    text = input("Enter text to translate: ")

# Upload text file
elif choice == "2":
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    with open(filename, "r", encoding="utf-8") as f:
        text = f.read()
    print("\n📄 Extracted text from file:")
    print(text)

# Upload image for OCR
elif choice == "3":
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    text = extract_text_from_image(filename)
    print("\n🖼️ OCR extracted text:")
    print(text)

else:
    print("Invalid choice!")
    text = ""

# If text was collected, then translate
if text:
    print("\nEnter target language code (hi, bn, en, es, fr, de, ta, te, ml, kn)")
    target = input("Language code: ")

    translated = translate_text(text, target)

    print("\n🔹 Translated Text:")
    print(translated)

# Install libraries
!pip install easyocr deep-translator pillow matplotlib

from deep_translator import GoogleTranslator
from google.colab import files
import easyocr
from PIL import Image
import matplotlib.pyplot as plt

reader = easyocr.Reader(['en'])  # OCR reader

# ------------------------------- #
# TRANSLATION FUNCTION
# ------------------------------- #
def translate_text(text, target_lang):
    return GoogleTranslator(source='auto', target=target_lang).translate(text)

# ------------------------------- #
# OCR FUNCTION
# ------------------------------- #
def extract_text_from_image(img_path):
    result = reader.readtext(img_path, detail=0)
    return " ".join(result)

# ------------------------------- #
# MAIN PROGRAM
# ------------------------------- #

print("Select an option:")
print("1 → Type text manually")
print("2 → Upload a text file (.txt)")
print("3 → Upload an image for OCR + translation")

choice = input("Enter 1/2/3: ")

# Manual text input
if choice == "1":
    text = input("Enter text to translate: ")

# Upload text file
elif choice == "2":
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    with open(filename, "r", encoding="utf-8") as f:
        text = f.read()
    print("\n📄 Extracted text from file:")
    print(text)

# Upload image for OCR
elif choice == "3":
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    text = extract_text_from_image(filename)
    print("\n🖼️ OCR extracted text:")
    print(text)

else:
    print("Invalid choice!")
    text = ""

# If text was collected, then translate
if text:
    print("\nEnter target language code (hi, bn, en, es, fr, de, ta, te, ml, kn)")
    target = input("Language code: ")

    translated = translate_text(text, target)

    print("\n🔹 Translated Text:")
    print(translated)